---
- hosts: webservers
  remote_user: cc
  become: yes

  tasks:
  - name: Clone openface git directory
    git:
      repo: https://github.com/cmusatyalab/openface.git
      dest: /home/cc/openface
      recursive: yes

  - name: Install software dependencies
    apt: pkg={{ item }} state=installed
    with_items:
      - build-essential
      - ipython
      - python-dev
      - python-pip
      - python-numpy
      - cmake
      - git
      - libgtk2.0-dev
      - pkg-config
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - python-numpy
      - python-scipy
      - libtbb2
      - libtbb-dev
      - libjpeg-dev
      - libpng-dev
      - libtiff-dev
      - libjasper-dev
      - libdc1394-22-dev
      - libboost-all-dev
      - python-pandas
      - python-opencv
      - libreadline-dev

  - name: Install other dependencies
    pip: name={{item}} 
    with_items:
      - scikit-learn 
      - dlib

  
  - name: Clone Torch Repository
    git:
        repo: https://github.com/torch/distro.git
        dest: /home/cc/torch
        recursive: yes
        force: yes
        accept_hostkey: yes

  - name: set permissions for directories
    file: path=/home/cc/openface state=directory owner=cc mode=0777
    file: path=/home/cc/torch state=directory owner=cc mode=0777

  - name: Install Torch
    shell: bash install-deps chdir=/home/cc/torch
    shell: cd /home/cc/torch; yes | ./install.sh

  - name: Source bashrc
    shell: source ~/.bashrc
    args: 
      executable: /bin/bash          	 
    
  - name: Install Openface
    become: yes
    shell: python2 setup.py install chdir=/home/cc/openface
    shell: models/get-models.sh chdir=/home/cc/openface

  - name: Create ubuntu directory
    file: path=/home/cc/ubuntu state=directory owner=cc mode=u+rwx
