---
- hosts: servers
  
  tasks:
  - name: Clone openface git directory
    git:
      repo: https://github.com/cmusatyalab/openface.git
      dest: ~/openface
      recursive: yes

  - name: Install software dependencies
    apt: pkg={{ item }} state=installed
    become: yes
    with_items:
      - build-essential
      - ipython
      - python-dev
      - python-pip
      - python-numpy
      - cmake
      - git
      - libgtk2.0-dev
      - pkg-config
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - python-numpy
      - python-scipy
      - libtbb2
      - libtbb-dev
      - libjpeg-dev
      - libpng-dev
      - libtiff-dev
      - libjasper-dev
      - libdc1394-22-dev
      - libboost-all-dev
      - python-pandas
      - python-opencv
      - libreadline-dev

  - name: Install additional dependencies
    pip: name={{item}}
    become: yes 
    with_items:
      - scikit-learn 
      - dlib
  
  - name: Clone torch repository
    git:
        repo: https://github.com/torch/distro.git
        dest: ~/torch
        recursive: yes
        force: yes
        accept_hostkey: yes

  - name: set permissions for directories
    file: path={{ item }} state=directory owner=cc group=cc mode=0777 recurse=yes
    with_items:
      - /home/cc/openface
      - /home/cc/torch

  - name: Install torch deps
    become_method: sudo
    shell: bash install-deps chdir=~/torch

  - name: Install torch
    become_method: sudo
    shell: bash install-deps chdir=~/torch

  - name: Source bashrc
    shell: source ~/.bashrc chdir=~/torch
    args:
      executable: /bin/bash 
  
  - name: Install torch dpnn
    become_method: sudo
    shell: ~/torch/install/bin/luarocks install dpnn

  - name: Install torch nn
    become_method: sudo
    shell: ~/torch/install/bin/luarocks install nn

  - name: Install torch optim
    become_method: sudo
    shell: ~/torch/install/bin/luarocks install optim

  - name: Install torch csvigo
    become_method: sudo
    shell: ~/torch/install/bin/luarocks install csvigo

  - name: Install torch cutorch
    become_method: sudo
    shell: ~/torch/install/bin/luarocks install cutorch

  - name: Install torch cunn
    become_method: sudo
    shell: ~/torch/install/bin/luarocks install cunn

  - name: Install torch fblualib
    become_method: sudo
    shell: ~/torch/install/bin/luarocks install fblualib

  - name: Install torch torchx
    become_method: sudo
    shell: ~/torch/install/bin/luarocks install torchx

  - name: Install torch optnet
    become_method: sudo
    shell: ~/torch/install/bin/luarocks install optnet

  - name: Install openface
    become_method: sudo
    shell: "{{ item }} chdir=~/openface"
    with_items:
      - python setup.py install
      - models/get-models.sh chdir=~/openface


 
