---
- hosts: servers
  
  tasks:
  - name: Clone openface git directory
    git:
      repo: https://github.com/cmusatyalab/openface.git
      dest: ~/openface
      recursive: yes

  - name: Install software dependencies
    apt: pkg={{ item }} state=installed
    become: yes
    with_items:
      - build-essential
      - ipython
      - python-dev
      - python-pip
      - python-numpy
      - cmake
      - git
      - libgtk2.0-dev
      - pkg-config
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - python-numpy
      - python-scipy
      - libtbb2
      - libtbb-dev
      - libjpeg-dev
      - libpng-dev
      - libtiff-dev
      - libjasper-dev
      - libdc1394-22-dev
      - libboost-all-dev
      - python-pandas
      - python-opencv
      - libreadline-dev

  - name: Install additional dependencies
    pip: name={{item}}
    become: yes 
    with_items:
      - scikit-learn 
      - dlib

  
  - name: Clone torch repository
    git:
        repo: https://github.com/torch/distro.git
        dest: ~/torch
        recursive: yes
        force: yes
        accept_hostkey: yes

  - name: set permissions for directories
    file: path={{ item }} state=directory owner=cc group=cc mode=0777 recurse=yes
    with_items:
      - /home/cc/openface
      - /home/cc/torch

  - name: Install torch
    tags: install_torch
    become_method: sudo
    shell: "{{ item }} chdir=~/torch"
    with_items:
      - bash install-deps
      - yes | ./install.sh

  - name: Source bashrc
    shell: source ~/.bashrc chdir=~/torch
    args:
      executable: /bin/bash 
  
  - name: Install torch dependencies
    become_method: sudo
    shell: ~/torch/install/bin/luarocks install {{ item }}
    with_items:
      - dpnn
      - nn
      - optim
      - csvigo
      - cutorch
      - cunn
      - fblualib
      - torchx
      - optnet

  - name: Install openface
    become_method: sudo
    shell: "{{ item }} chdir=~/openface"
    with_items:
      - python setup.py install
      - models/get-models.sh chdir=~/openface


 
