---
- hosts: webservers1
  
  tasks:
  - name: Clone openface git directory
    git:
      repo: https://github.com/cmusatyalab/openface.git
      dest: ~/openface
      recursive: yes

  - name: Install software dependencies
    apt: pkg={{ item }} state=installed
    become: yes
    with_items:
      - build-essential
      - ipython
      - python-dev
      - python-pip
      - python-numpy
      - cmake
      - git
      - libgtk2.0-dev
      - pkg-config
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - python-numpy
      - python-scipy
      - libtbb2
      - libtbb-dev
      - libjpeg-dev
      - libpng-dev
      - libtiff-dev
      - libjasper-dev
      - libdc1394-22-dev
      - libboost-all-dev
      - python-pandas
      - python-opencv
      - libreadline-dev

  - name: Install other dependencies
    pip: name={{item}}
    become: yes 
    with_items:
      - scikit-learn 
      - dlib

  
  - name: Clone Torch Repository
    git:
        repo: https://github.com/torch/distro.git
        dest: ~/torch
        recursive: yes
        force: yes
        accept_hostkey: yes

  - name: set permissions for directories
    file: path=/home/cc/openface state=directory owner=cc group=cc mode=0777 recurse=yes
    file: path=/home/cc/torch state=directory owner=cc group=cc mode=0777 recurse=yes

  - name: Install Torch
    become_method: sudo
    shell: bash install-deps chdir=~/torch
    shell: yes | ./install.sh chdir=~/torch

  - name: Source bashrc
    shell: source ~/.bashrc chdir=~/torch
    args:
      executable: /bin/bash 
  
  - name: Install Torch dependencies
    become_method: sudo
    shell: ~/torch/install/bin/luarocks install dpnn
    shell: ~/torch/install/bin/luarocks install nn
    shell: ~/torch/install/bin/luarocks install optim
    shell: ~/torch/install/bin/luarocks install csvigo
    shell: ~/torch/install/bin/luarocks install cutorch 
    shell: ~/torch/install/bin/luarocks install cunn
    shell: ~/torch/install/bin/luarocks install fblualib
    shell: ~/torch/install/bin/luarocks install torchx
    shell: ~/torch/install/bin/luarocks install optnet 

  - name: Install openface
    become_method: sudo
    shell: python setup.py install chdir=~/openface
    shell: models/get-models.sh chdir=~/openface


 
